In [4]:
import numpy as np 
student = np.array([('mariam', 150, "AI"),("Ahmed",180,"mopile"),('yassmin', 155, "AI")], 
dtype=[('name', (np.str_, 20)), ('height', np.int32), ('class', np.str_,10)]) 

# Sorting according to the age 
sortarray = np.sort(student, order='height') 
print('\nSorting according to the heigh', sortarray)



Sorting according to the heigh [('mariam', 150, 'AI') ('yassmin', 155, 'AI') ('Ahmed', 180, 'mopile')]


In [7]:
a=np.array([[1,2,-3,2],[2,-5,4,9],[-5,40,-1,-20],[5,-4,-1,60]])
b=([30,4,-6,5])
np.linalg.solve(a,b)

array([19.46701571,  1.44371728, -3.54973822, -1.50183246])

In [8]:
from scipy import linalg

In [52]:
a1=np.array([[1,2,-3,2],[2,-5,4,9],[-5,40,-1,-20],[5,-4,-1,60]])
b1=([30,4,-6,5])

res=linalg.solve(a1,b1)
print(res)

[19.46701571  1.44371728 -3.54973822 -1.50183246]


In [13]:
res2=a.dot(res)
print(res2)

[30.  4. -6.  5.]


In [26]:
y=[1,2,3,4,5,6]
yhat=[1.2,2,3.1,4.02,5.001,5.98]
numb=len(y)
sum=0
for i in range (numb):
    sum +=np.absolute(y[i]-yhat[i])
print(sum)

0.3409999999999995


In [27]:
y2=[1,2,3,4,5,6]
yhat2=[1.2,2,3.1,4.02,5.001,5.98]
numb=len(y)
sum=0
for i in range (numb):
    sum +=np.square(y[i]-yhat[i])
print(sum)

0.050800999999999964


In [28]:
import time

In [59]:
%%time
for i in range(100_000):
    np.dot(y,y2)

CPU times: total: 406 ms
Wall time: 463 ms


In [58]:
%%time
res3=0
for i in range(100_100):
    for i in range (len(y)):
        res+=y[i]*y2[i]


CPU times: total: 1.17 s
Wall time: 1.19 s


In [60]:
%%time
from multiprocessing import Process
for i in range(100_100):
    def calcdot(a1,a2):
        np.dot(a1,a2)

if __name__ == '__main__':
    p = Process(target=calcdot, args=(y,y2))
    p.start()
    p.join()

CPU times: total: 0 ns
Wall time: 178 ms
