# LAB 1: Matrix and Vector Computations in python
In this lab you will use python to study the following topics:

- How to create matrices and vectors in python.

- How to manipulate matrices in python and create matrices of special types.

- How to add matrices and multiply a vector by a matrix by python.

- Solving System of Linear Equations Using Gaussian Elimination.

- Matrix Multiplication using Different views.

# First: you should run this cell

In [ ]:
# Make all numpy available via shorter 'np' prefix
import numpy as np

import sympy as sym

# Question 1 :Declaring scalars, vectors, and matrices

a) Use [numpy.array](https://numpy.org/doc/stable/reference/generated/numpy.array.html) to declare the following:

1. A scalar $s = 5$
2. A vector $v = \begin{bmatrix} 5  \\ -2 \\ 4  \\ \end{bmatrix}$
3. A matrix $A = \begin{bmatrix} 1 & 2 & 3  \\ 4 & 5 & 6 \\ 7 & 8 & 9  \\ \end{bmatrix}$
4. A matrix $B = \begin{bmatrix} 1 & 2 & 3  \\ 4 & 5 & 6 \\ \end{bmatrix}$
5. A matrix $C = \begin{bmatrix} 1 & 2   \\ 3 & 4  \\ 5 & 6   \\ \end{bmatrix}$

In [ ]:
s =np.array(5)
print("s = ",s)

s =  5


In [ ]:
v=np.array([5,-2,4])
v=v.reshape(3,1)
print("v= \n", v)

v= 
 [[ 5]
 [-2]
 [ 4]]


In [ ]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("A= \n", A)

A= 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
B=np.array([[1,2,3],[4,5,6]])
print("B= \n", B)

B= 
 [[1 2 3]
 [4 5 6]]


In [ ]:
C=np.array([[1,2],[3,4],[5,6]])
print("C= \n", C)

C= 
 [[1 2]
 [3 4]
 [5 6]]


In [ ]:
#type your code here:


s = 5

v =
 [[ 5]
 [-2]
 [ 4]]

A =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

B =
 [[1 2 3]
 [4 5 6]]

C =
 [[1 2]
 [3 4]
 [5 6]]



b) Print the data type of $s, v,$ and $A$ using `type` command in python.

In [ ]:
print(type(s),"\n")
print(type(v),"\n")
print(type(A),"\n")
print(type(B),"\n")
print(type(C),"\n")


<class 'numpy.ndarray'> 

<class 'numpy.ndarray'> 

<class 'numpy.ndarray'> 

<class 'numpy.ndarray'> 

<class 'numpy.ndarray'> 



In [ ]:
#type your code here:


type(s) = <class 'numpy.ndarray'>

type(v) = <class 'numpy.ndarray'>

type(A) = <class 'numpy.ndarray'>



c) Using [numpy.shape](https://numpy.org/devdocs/reference/generated/numpy.shape.html) or `A.shape` print the shape of $s, v, A, B,$ and $C$.

In [ ]:
print("s.shape = ",s.shape,"\n")
print("x.shape = ",v.shape,"\n")
print("y.shape = ",A.shape,"\n")
print("z.shape = ",B.shape,"\n")
print("m.shape = ",C.shape,"\n")


s.shape =  () 

x.shape =  (3, 1) 

y.shape =  (3, 3) 

z.shape =  (2, 3) 

m.shape =  (3, 2) 



In [ ]:
#type your code here:


s.shape = ()

v.shape = (3, 1)

A.shape = (3, 3)

B.shape = (2, 3)

C.shape = (3, 2)



d) To access a given entry in the `numpy array` put the `row number - 1` and `column number - 1` in square brackets following the array name. Ex `a32 = A[2, 1]`.
- Print the value of the third row and the second column of the matrix $A$.
- Change it to $10$.
- Print the matrix A to check the entry is changed.

In [ ]:
print(A,"\n")
print(A[2,1])


[[1 2 3]
 [4 5 6]
 [7 8 9]] 

8


In [ ]:
A[2,1]=10
print("A= \n",A)

A= 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7 10  9]]


In [ ]:
#type your code here:


A[2, 1] =  8

A =
 [[ 1  2  3]
 [ 4  5  6]
 [ 7 10  9]]



e)To access a whole row or column of a matrix, use the colon operator. For example, `A[:, [1]]` is the second column of A, while `B[[1], :]` is the second row of B.

In [ ]:
print(A[:,[1]],"\n")
print(B[[1],:])

[[ 2]
 [ 5]
 [10]] 

[[4 5 6]]


In [ ]:
#type your code here:


A[:, [1]] =
 [[ 2]
 [ 5]
 [10]]

B[[1], :] =
 [[4 5 6]]



f) Type each of the following commands that generate special matrices:
- `np.eye(4), np.zeros(3), np.zeros((3, 1)), np.zeros((3, 5)), np.ones((2, 3)), and np.diag([4, 5, 6, 7])`

In [ ]:
np.eye(4) #matrix with 4*4 dimentions and the diagonal is all ones

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.zeros(3) #matrix 0f 1*3

array([0., 0., 0.])

In [ ]:
np.zeros((3, 1))

array([[0.],
       [0.],
       [0.]])

In [ ]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.diag([4, 5, 6, 7]) #all the other cells are zeros

array([[4, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 7]])

In [ ]:
#type your code here:


np.eye(4) =
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

np.zeros(3) =
 [0. 0. 0.]

np.zeros(3, 1) =
 [[0.]
 [0.]
 [0.]]

np.zeros(3, 5) =
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

np.ones(2, 3) =
 [[1. 1. 1.]
 [1. 1. 1.]]

np.diag([4 5 6 7]) =
 [[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 7]]


# Question 2. Vectors Addition, Scaling, and dot product

a) Declare vectors $v1 = \begin{bmatrix} 1  \\ 2 \\ 7  \\ 4 \\ \end{bmatrix}$ and $v2 = \begin{bmatrix} 4  \\ 3 \\ 6  \\ 8 \\ \end{bmatrix}$

- Addition: $v1 + v2$
- Subtraction: $v1 - v2$
- Scaling by a number: $3 * v1$
- Scaling by a number: $v1 / 2$

In [ ]:
v1=np.array([1,2,7,4])
v2=np.array([4,3,6,8])
v1=v1.reshape(4,1)
v2=v2.reshape(4,1)
print(v1,"\n")
print(v2,"\n")

[[1]
 [2]
 [7]
 [4]] 

[[4]
 [3]
 [6]
 [8]] 



In [ ]:
print(v1+v2,"\n")
print(v1-v2,"\n")
print(3*v1,"\n")
print(v1/2,"\n")

[[ 5]
 [ 5]
 [13]
 [12]] 

[[-3]
 [-1]
 [ 1]
 [-4]] 

[[ 3]
 [ 6]
 [21]
 [12]] 

[[0.5]
 [1. ]
 [3.5]
 [2. ]] 



In [ ]:
#type your code here:


v1 =
 [[1]
 [2]
 [7]
 [4]]

v2 =
 [[4]
 [3]
 [6]
 [8]]

v1 + v2 =
 [[ 5]
 [ 5]
 [13]
 [12]]

v1 - v2 =
 [[-3]
 [-1]
 [ 1]
 [-4]]

3*v1 =
 [[ 3]
 [ 6]
 [21]
 [12]]

v1/2 =
 [[0.5]
 [1. ]
 [3.5]
 [2. ]]



b) Find the dot product between the two vectors $v1$ and $v2$ using the following:

- [numpy.dot](https://numpy.org/doc/stable/reference/generated/numpy.dot.html)
- [numpy.matmul](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html#numpy.matmul)
- `v1.T @ v2`

In [ ]:
v1=v1.T

In [ ]:
v1.dot(v2)

array([[84]])

In [ ]:
np.matmul(v1,v2)

array([[84]])

In [ ]:
v3=v1@v2
print(v3)

[[84]]


In [ ]:
#type your code here:


Using numpy.dot =
 [[84]]

Using numpy.matmul =
 [[84]]

Using @ =
 [[84]]



c) Find the length of the vectors $v1$ and $v2$.
- Using [numpy.linalg.norm](https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html)
- Using the dot product and [numpy.sqrt](https://numpy.org/doc/stable/reference/generated/numpy.sqrt.html)


In [ ]:
print(v1.T)

[[1]
 [2]
 [7]
 [4]]


In [ ]:
np.linalg.norm(v1)
np.linalg.norm(v2)

11.180339887498949

In [ ]:
length_v1= np.sqrt(np.dot(v1.T, v1)) #first dot v1 and v1 then you have the norm **2 so we take the sqrt
length_v2= np.sqrt(np.dot(v2.T, v2))
print(length_v1)
print(length_v2)

[[8.36660027]]
[[11.18033989]]


In [ ]:
#type your code here:


length of v1 Using numpy.linalg.norm =
 8.366600265340756

length of v2 Using numpy.linalg.norm =
 11.180339887498949

length of v1 Using the dot product and numpy.sqrt =
 [[8.36660027]]

length of v2 Using the dot product and numpy.sqrt =
 [[11.18033989]]



d) Show that the vectors $u = \begin{bmatrix} 3  \\ 2 \\ -1  \\ 4 \\ \end{bmatrix}$ and $v = \begin{bmatrix} 1  \\ -1 \\ 1  \\ 0 \\ \end{bmatrix}$ are orthogonal.


In [ ]:
u=np.array([3,2,-1,4])
v=np.array([1,-1,1,0])
u.reshape(4,1)


array([[ 3],
       [ 2],
       [-1],
       [ 4]])

In [ ]:
u@v #  هيبقى بصفر وبالتالي ناتج الدوت هيبقى بصفر لcos المتعامدين ناتج ال

0

In [ ]:
#type your code here:


u.T @ v =
 [[0]]



# Question 3. Matrix Addition and Matrix-Vector Multiplication

Declare vectors $u$ and $v$ and matrices $A$ and $B$ as following:
- $u = \begin{bmatrix} 2  \\ 7 \\ 2 \\ \end{bmatrix}$, $v = \begin{bmatrix} 8  \\ 2 \\ 4 \\ \end{bmatrix}$
- $A = \begin{bmatrix} 7 & 3 & 5  \\ 4 & 6 & 2 \\ \end{bmatrix}$, $B = \begin{bmatrix} 0 & 6 & 4  \\ 2 & 3 & 0 \\ \end{bmatrix}$

a) Calculate the following using python.

- $A+B$
- $B+A$
- $3A$
- $6B$
- $2(3B)$
- $6A+15B$
- $3(2A+5B)$
- $(3A^T)^T$

In [ ]:
u=np.array([2,7,2])
u=u.reshape(3,1)
v=np.array([8,2,4])
v=v.reshape(3,1)
A=np.array([[7,3,5],[4,6,2]])
B=np.array([[0,6,4],[2,3,0]])

In [ ]:
print(A+B)


[[7 9 9]
 [6 9 2]] 



In [ ]:
print(B+A)

[[7 9 9]
 [6 9 2]] 



In [ ]:
print(3*A)

[[21  9 15]
 [12 18  6]]


In [ ]:
print(6*B)

[[ 0 36 24]
 [12 18  0]]


In [ ]:
print(2*(3*B))

[[ 0 36 24]
 [12 18  0]]


In [ ]:
print(6*A+15*B)

[[ 42 108  90]
 [ 54  81  12]]


In [ ]:
print(2*A)

[[14  6 10]
 [ 8 12  4]]


In [ ]:
print(5*B)

[[ 0 30 20]
 [10 15  0]]


In [ ]:
print(2*A+5*B)

[[14 36 30]
 [18 27  4]]


In [ ]:
print(3*(2*A+5*B))

[[ 42 108  90]
 [ 54  81  12]]


In [ ]:
#type your code here:
print(3*A)

[[21  9 15]
 [12 18  6]]


In [ ]:
print((3*A.T).T)

[[21  9 15]
 [12 18  6]]


b) To obtain the matrix-vector product $Au$ using python, type `A @ u`. Calculate the following:

- $Au+Av$
- $A(u+v)$
- $(A+B)u$
- $Au+Bu$
- $A(3u)$
- $3A(u)$

In [ ]:
print(A@u+A@v) #brodcasting starting (3,1)(2,3)->(1,3)(3,2) #reshape so can make dot product

[[127]
 [106]]


In [ ]:
print(A@(u+v)) #the same input

[[127]
 [106]]


In [ ]:
print((A+B)@u) #brodcasting

[[95]
 [79]]


In [ ]:
print(A@u+B@u) #the same output

[[95]
 [79]]


In [ ]:
print(A@(3*u)) #brodcasting

[[135]
 [162]]


In [ ]:
print(3*(A@u)) #the same output

[[135]
 [162]]


In [ ]:
#type your code here:


Au + Av =
 [[127]
 [106]]

A(u + v) =
 [[127]
 [106]]

(A + B)u =
 [[95]
 [79]]

Au + Bu =
 [[95]
 [79]]

A(3u) =
 [[135]
 [162]]

3A(u) =
 [[135]
 [162]]



# Question 4. Gaussian Elimination and Reduced Row-Echelon Form

You will see a step-by-step example of the row operations that transform a matrix $A$ into its reduced row echelon form $R = rref(A)$. In this demonstration, each pivot is chosen to be the largest in its column (for numerical stability), so extra row interchanges are used. Since $rref(A)$ is uniquely determined by $A$, this does not affect the final answer.

The built in [rref](https://docs.sympy.org/latest/tutorial/matrices.html#rref) method `sympy.rref()` method just search for the method and its output to deal with the code.

#### (a) Generate and display a $3 \times 4$ matrix $A$ with random integer entries

In [ ]:
#type your code here:
A = np.fix((10*(np.random.rand(3,4)))) #fix use to round the rondom number so it be int
print("\n A = \n", A)


 A = 
 [[9. 3. 5. 8.]
 [1. 3. 9. 1.]
 [8. 9. 0. 0.]]


- To transform $A$ into $R = rref(A)$, start with $R = A$.
- Normalize the first row of R to get R(1st row, 1st column) = 1

    - `R = A`
    - `R[0,:] = R[0, :] / R[0, 0]`

(note the use of the colon to operate on whole rows of the matrix).

<div class="alert alert-block alert-warning">If your random matrix happens to have A(1, 1) = 0, then interchange rows to get a nonzero entry in the (1, 1) position before doing the calculation above.</div>

- Now subtract a multiple of the first row of R from the second row to make R(2, 1) = 0:

    - `R[1, :] = R[1, :] - R[1, 0] * R[0, :]`

- Repeat this procedure to make R(3, 1) = 0:

    - `R[2, :] = R[2, :] - R[2, 0] * R[0, :]`

The first column of your matrix $R$ should now be the same as the first column of $rref(A)$.

In [ ]:
#type your code here:




 R = 
 [[ 1.          0.          0.          0.20945946]
 [ 0.          1.          0.          1.01351351]
 [ 0.          0.          1.         -0.16891892]]


In [ ]:
R=A

In [ ]:
R[0,:]=R[0,:]-R[0,1] #make the second element in first row =zero
print(A)

[[ 0.66666667  0.          0.22222222  0.55555556]
 [ 0.          1.          3.16666667  0.04166667]
 [-0.         -0.          1.          0.30102041]]


In [ ]:
R[1,:]=R[1,:]-R[1,2] #make the third element in second row =zero
print(A)

[[ 0.66666667  0.          0.22222222  0.55555556]
 [-3.16666667 -2.16666667  0.         -3.125     ]
 [-0.         -0.          1.          0.30102041]]


In [ ]:
R[0,:]=R[0,:]*R[1,:] #make the third element in first row =zero
print(A)

[[-2.11111111 -0.          0.         -1.73611111]
 [-3.16666667 -2.16666667  0.         -3.125     ]
 [-0.         -0.          1.          0.30102041]]


In [ ]:
R[ 0,:] = R[0, :] / R[0, 0] #first row = first row divided by the first element to make first element =zero
print(R)


[[ 1.          0.         -0.          0.82236842]
 [-3.16666667 -2.16666667  0.         -3.125     ]
 [-0.         -0.          1.          0.30102041]]


In [ ]:
R[1, :] = R[1, :]-R[1,0]* R[0, :]
print(R)

[[ 1.          0.         -0.          0.82236842]
 [ 0.         -2.16666667  0.         -0.52083333]
 [-0.         -0.          1.          0.30102041]]


In [ ]:
R[2, :] = R[2, :] - R[2, 0] * R[0, :]
print(R)

[[ 1.          0.         -0.          0.82236842]
 [ 0.         -2.16666667  0.         -0.52083333]
 [ 0.          0.          1.          0.30102041]]


In [ ]:
R[1,:] = R[1, :] / R[1, 1]
print(R)

[[ 1.          0.         -0.          0.82236842]
 [-0.          1.         -0.          0.24038462]
 [ 0.          0.          1.          0.30102041]]


In [ ]:
R[2,:]=R[2,:]+R[1,:]*-1*R[2,1]
print(R)

[[ 1.          0.         -0.          0.82236842]
 [-0.          1.         -0.          0.24038462]
 [ 0.          0.          1.          0.30102041]]


In [ ]:
R[2,:] = R[2, :] / R[2, 2]
print(R)

[[ 1.          0.         -0.          0.82236842]
 [-0.          1.         -0.          0.24038462]
 [ 0.          0.          1.          0.30102041]]


**the end of the matrix --------------------**

In [ ]:
#type your code here:



 R = 
 [[ 1.     0.     0.5    0.125]
 [ 0.     6.    -1.     6.25 ]
 [ 0.     1.     6.     0.   ]]


#### (b)Operate on $R$ by the same method as in (a) to obtain the second column of $rref(A)$. First normalize row $2$ of $R$, then subtract multiples of row $2$ from rows $1$ and $3$ to put zeros in the (1, 2) and (3, 2) positions. Be sure to refer to the entries in your matrix symbolically as was done in part (a)

In [ ]:
#all the operation in matrix is above

In [ ]:
#type your code here:



 R = 
 [[ 1.          0.          0.5         0.125     ]
 [ 0.          1.         -0.16666667  1.04166667]
 [ 0.          0.          6.16666667 -1.04166667]]


#### (c) Operate on $R$ by the same method as in (b) to obtain the third column of $rref(A)$. First normalize row $3$ of $R$, then subtract multiples of row $3$ from rows $1$ and $2$ to put zeros in the (1, 3) and (2, 3) positions.

In [ ]:
#all the operation in matrix is above

#### (d) Your matrix $R$ should now be transformed into $rref(A)$ (since $A$ is a random $3 \times 4$ matrix, $rref(A)$ is (almost) sure to have rank (3) `np.linalg.matrix_rank(R)`. Check your answer by python with the rref method . If the answer is not the same as the current value of your $R$, go back and redo your calculations.

- use the the built in rref method `sympy.rref()`
- print the output matrix in numpy array type

    - `M = sym.Matrix(A)`
    - `M_rref = M.rref()`
    - `R = np.array((M_rref[0])).astype(np.float64)`

In [ ]:
np.linalg.matrix_rank(R)

3

In [ ]:
m=sym.Matrix(A)
m_rref=m.rref()
R=np.array((m_rref[0])).astype(np.float64)
print(R)

[[1.         0.         0.         0.82236842]
 [0.         1.         0.         0.24038462]
 [0.         0.         1.         0.30102041]]


In [ ]:
#type your code here:

# Use sympy.rref() method



 rank = 
 3

 The Row echelon form of matrix M 
 [[ 1.          0.          0.          0.20945946]
 [ 0.          1.          0.          1.01351351]
 [ 0.          0.          1.         -0.16891892]]


# Question 5. Matrix Multiplication using Different views

we discussed in the lecture four different ways about product $AB = C$ where $A$ and $B$ are arbitry matrices. If $A$ is an $m \times n$ matrix and $B$ is an $n \times p$ matrix, then $C$ is an $m \times p$ matrix:

1. **Standard(row times column):** The standard way of describing a matrix product is to say that $c_(ij)$ equals the dot product of row $i$ of matrix $A$ and column $j$ of matrix $B$.

2. **Columns:** The product of matrix $A$ and column $j$ of matrix $B$ equals column $j$ of matrix  $C$. This tells us that the columns of $C$ are combinations of columns of $A$.

3. **Rows:** The product of row $i$ of matrix $A$ and matrix $B$ equals row $i$ of matrix $C$.So the rows of $C$ are combinations of rows of $B$.

4. **Column times row**: A column of $A$ is an $m \times 1$ vector and a row of $B$ is a $1 \times p$ vector.Their product is a matrix.

In this problem we will use python to perform the matrix multiplication using these different ways, and compute the execution time for each method time.

(Write your code as a function that perform the multiplication for arbitrary size of the matrices $A$ and $B$)

In [305]:
A = np.array([[12., 7., 3.],[4., 5., 6.],[7., 8., 9.]])
B = np.array([[5., 8., 1., 9.],[6., 7., 3., 9.],[4., 5., 9., 9.]])

m, n = A.shape
n, p = B.shape

C = np.zeros((m, p))

print(A.dot(B))

for i in range(p):
    C[:, i] = np.dot(A, B[:, i])
print(C)
for i in range(m):
      C[i, :] = np.dot(A[i, :], B)
print(C)


print(C)

[[114. 160.  60. 198.]
 [ 74.  97.  73. 135.]
 [119. 157. 112. 216.]]
[[114. 160.  60. 198.]
 [ 74.  97.  73. 135.]
 [119. 157. 112. 216.]]
[[114. 160.  60. 198.]
 [ 74.  97.  73. 135.]
 [119. 157. 112. 216.]]
[[114. 160.  60. 198.]
 [ 74.  97.  73. 135.]
 [119. 157. 112. 216.]]


In [313]:
def check_dimension(A, B):
    return A.shape[1] == B.shape[0]

def mat_mul_standard(A, B):
    if not check_dimension(A, B):
        raise Exception('Dimensions aren\'t consistant')

    m, n = A.shape
    n, p = B.shape

    C = np.zeros((m, p))
    ################type your code here#####################
    C=A@B

    ########################################################
    return C


def mat_mul_columns(A, B):
    if not check_dimension(A, B):
        raise Exception('Dimensions aren\'t consistant')

    m, n = A.shape
    n, p = B.shape

    C = np.zeros((m, p))
    ################type your code here#####################
    for i in range(p):
      C[:, i] = np.dot(A, B[:, i])

    ########################################################
    return C

def mat_mul_rows(A, B):
    if not check_dimension(A, B):
        raise Exception('Dimensions aren\'t consistant')

    m, n = A.shape
    n, p = B.shape

    C = np.zeros((m, p))
    ################type your code here#####################
    for i in range(m):
        C[i, :] = np.dot(A[i, :], B)
    ########################################################
    return C



def mat_mul_column_times_row(A, B):
    if not check_dimension(A, B):
        raise Exception('Dimensions aren\'t consistant')

    m, n = A.shape
    n, p = B.shape

    C = np.zeros((m, p))
    ################type your code here#####################


    for k in range(n):  # Loop over shared dimension
        C += A[:, k].reshape(-1, 1) @ B[k, :].reshape(1, -1) #بضرب اول عمود فى اول صف وبعمل ليه ريشاب عشان ينفع الضرب وهكذا لكل عمود بعده
    ########################################################
    return C

In [307]:
#A = np.array([[12., 7., 3.],[4., 5., 6.],[7., 8., 9.]])
#B = np.array([[5., 8., 1., 2.],[6., 7., 3., 0.],[4., 5., 9., 1.]])

A = np.fix((10*(np.random.rand(300, 300))))
B = np.fix((10*(np.random.rand(300, 300))))

In [308]:
%%time
print('A @ B = \n', A @ B)

A @ B = 
 [[6269. 6739. 6211. ... 5760. 6280. 5900.]
 [5843. 6033. 5837. ... 5146. 5860. 5777.]
 [5884. 6197. 5818. ... 5393. 5695. 5602.]
 ...
 [5863. 6176. 5735. ... 5418. 5694. 5641.]
 [6018. 6622. 6198. ... 5821. 5693. 5989.]
 [6258. 6446. 6304. ... 5774. 6192. 6194.]]
CPU times: user 6 ms, sys: 3.1 ms, total: 9.1 ms
Wall time: 7.02 ms


In [309]:
%%time
C_standard = mat_mul_standard(A, B)
print('C_standard = \n', C_standard)

C_standard = 
 [[6269. 6739. 6211. ... 5760. 6280. 5900.]
 [5843. 6033. 5837. ... 5146. 5860. 5777.]
 [5884. 6197. 5818. ... 5393. 5695. 5602.]
 ...
 [5863. 6176. 5735. ... 5418. 5694. 5641.]
 [6018. 6622. 6198. ... 5821. 5693. 5989.]
 [6258. 6446. 6304. ... 5774. 6192. 6194.]]
CPU times: user 7.46 ms, sys: 2.99 ms, total: 10.5 ms
Wall time: 5.45 ms


In [310]:
%%time
C_columns = mat_mul_columns(A, B)
print('C_columns = \n', C_columns)

C_columns = 
 [[6269. 6739. 6211. ... 5760. 6280. 5900.]
 [5843. 6033. 5837. ... 5146. 5860. 5777.]
 [5884. 6197. 5818. ... 5393. 5695. 5602.]
 ...
 [5863. 6176. 5735. ... 5418. 5694. 5641.]
 [6018. 6622. 6198. ... 5821. 5693. 5989.]
 [6258. 6446. 6304. ... 5774. 6192. 6194.]]
CPU times: user 12.5 ms, sys: 6.3 ms, total: 18.8 ms
Wall time: 26.2 ms


In [311]:
%%time
C_rows = mat_mul_rows(A, B)
print('C_rows = \n', C_rows)

C_rows = 
 [[6269. 6739. 6211. ... 5760. 6280. 5900.]
 [5843. 6033. 5837. ... 5146. 5860. 5777.]
 [5884. 6197. 5818. ... 5393. 5695. 5602.]
 ...
 [5863. 6176. 5735. ... 5418. 5694. 5641.]
 [6018. 6622. 6198. ... 5821. 5693. 5989.]
 [6258. 6446. 6304. ... 5774. 6192. 6194.]]
CPU times: user 16.2 ms, sys: 8.12 ms, total: 24.3 ms
Wall time: 19.9 ms


In [314]:
%%time
C_column_times_row = mat_mul_column_times_row(A, B)
print('C_column_times_row = \n', C_column_times_row)

C_column_times_row = 
 [[6269. 6739. 6211. ... 5760. 6280. 5900.]
 [5843. 6033. 5837. ... 5146. 5860. 5777.]
 [5884. 6197. 5818. ... 5393. 5695. 5602.]
 ...
 [5863. 6176. 5735. ... 5418. 5694. 5641.]
 [6018. 6622. 6198. ... 5821. 5693. 5989.]
 [6258. 6446. 6304. ... 5774. 6192. 6194.]]
CPU times: user 88.2 ms, sys: 748 µs, total: 89 ms
Wall time: 95.2 ms
